### ISSUE TITLE
spot-the-diff 

### ISSUE THREAD

**Issue by Amark-cheey** [tuyunbin/VARD#2]
I found that there are many similar empty representations in the spot dataset, such as {"img_id": "10644", "sentences": [""]}, {"img_id": "10645", "sentences": ["there are people now"]}, {"img_id": "12201", "sentences": [""]}. How did the author handle this part of the data?

**Comment by tuyunbin** [comment]
For the image pair without captions, I add the special token "PAD" when making the labels. Your can refer to my another repository (https://github.com/tuyunbin/CARD) where the spot-the-diff dataset has been uploaded.
